### ISSUE TITLE
Reordering of columns within sheet

### ISSUE THREAD

**Issue by ydyote** [afterschoolstudio/Depot#58] opened 2023-05-08 14:22 UTC
It would be nice to be able to reorder columns within the sheet
And then I guess that would also mean reordering on different levels separately

Ofc it should also reorder the data within the json

Nice extension, good idea, keep it up

**Comment by kkukshtel** [comment] 2023-09-19 15:20
Closing as duplicate of #34

**Closed by kkukshtel** 2023-09-19 15:20 UTC
Labels: enhancement
